<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="*" ExcludeAssets="runtime" />
    <Reference Include="LevelsRanksApi">
      <HintPath>LevelsRanksApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FakeRanksApi">
      <HintPath>FakeRanksApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
